name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/yt-dlp/yt-dlp.git || true

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Check for new commits
        id: check_commits
        run: |
          UPSTREAM_SHA=$(git rev-parse upstream/master)
          ORIGIN_SHA=$(git rev-parse origin/master)
          if [ "$UPSTREAM_SHA" = "$ORIGIN_SHA" ]; then
            echo "No new commits in upstream"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "New commits found in upstream"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Rebase onto upstream
        if: steps.check_commits.outputs.has_changes == 'true'
        run: |
          git checkout master
          if git rebase upstream/master; then
            echo "✅ Rebase successful"
          else
            echo "❌ Rebase failed due to conflicts"
            git rebase --abort
            exit 1
          fi

      - name: Push changes
        if: steps.check_commits.outputs.has_changes == 'true'
        run: git push origin master
